name: injury_atlas
channels:
  - apple
  - conda-forge
  - bioconda
  - pytorch
  - r
  - defaults
dependencies:
  - absl-py=1.4.0
  - anndata=0.8.0
  - aom=3.5.0
  - appnope=0.1.3
  - arpack=3.7.0
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - atk-1.0=2.38.0
  - attrs=23.1.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.6
  - aws-c-io=0.13.19
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.7
  - aws-c-sdkutils=0.1.8
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.8
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - biopython=1.81
  - blosc=1.21.3
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.8.0
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cellrank=2.0.0
  - certifi=2024.6.2
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - chex=0.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contextlib2=21.6.0
  - contourpy=1.0.7
  - cryptography=40.0.1
  - cycler=0.11.0
  - dask-core=2023.8.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - dm-tree=0.1.7
  - docrep=0.3.2
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - faiss-cpu=1.7.4
  - fbpca=1.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.10.7
  - flax=0.6.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.3.0
  - fst-pso=1.8.1
  - future=0.18.3
  - fuzzytm=2.0.5
  - gdk-pixbuf=2.42.10
  - gensim=4.3.2
  - geosketch=1.2
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.76.2
  - glib-tools=2.76.2
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graph-tool-base=2.48
  - graphite2=1.3.13
  - graphviz=7.1.0
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - gtk2=2.24.33
  - gts=0.7.6
  - h5py=3.6.0
  - harfbuzz=6.0.0
  - harmonypy=0.0.6
  - hdf5=1.12.1
  - hypre=2.25.0
  - icu=70.1
  - idna=3.4
  - igraph=0.10.3
  - imagecodecs=2023.1.23
  - imageio=2.34.0
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - importlib_resources=6.0.0
  - intervaltree=3.1.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipywidgets=8.0.6
  - jax=0.4.8
  - jaxlib=0.4.7
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.18.6
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.7
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.15
  - leidenalg=0.9.1
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarrow=11.0.0
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libcxx=16.0.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libfaiss=1.7.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libgoogle-cloud=2.8.0
  - libgrpc=1.52.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightning-utilities=0.8.0
  - llvm-openmp=16.0.0
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - metis=5.1.0
  - miniful=0.0.6
  - ml-collections=0.1.1
  - ml_dtypes=0.0.4
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpi=1.0
  - mpi4py=3.1.4
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - mudata=0.2.1
  - multipledispatch=0.6.0
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - natsort=8.3.1
  - nbformat=5.9.2
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - node2vec=0.3.0
  - nspr=4.35
  - nss=3.89
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.22.4
  - numpyro=0.11.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openmpi=4.1.5
  - openpyxl=3.1.1
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - optax=0.1.4
  - orc=1.8.3
  - p11-kit=0.24.1
  - packaging=23.0
  - pandarallel=1.6.5
  - pango=1.50.14
  - parmetis=4.0.3
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - petsc=3.17.3
  - petsc4py=3.17.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - ply=3.11
  - pooch=1.7.0
  - progressbar2=4.2.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptscotch=6.0.9
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=11.0.0
  - pybiomart=0.2.0
  - pycairo=1.23.0
  - pycparser=2.21
  - pyfume=0.2.25
  - pygments=2.14.0
  - pygpcca=1.0.4
  - pygraphviz=1.10
  - pynndescent=0.5.8
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyro-api=0.1.2
  - pyro-ppl=1.8.4
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.10
  - python-annoy=1.17.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-lightning=1.9.4
  - pytz=2023.3
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - re2=2023.02.02
  - readline=8.2
  - referencing=0.30.0
  - requests=2.28.2
  - requests_cache=0.4.13
  - rich=13.3.3
  - rpds-py=0.9.2
  - rust=1.67.1
  - rust-std-aarch64-apple-darwin=1.67.1
  - scalapack=2.2.0
  - scanorama=1.7.3
  - scanpy=1.9.3
  - schist=0.7.16
  - scikit-image=0.21.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - scotch=6.0.9
  - scrublet=0.2.3
  - scvelo=0.2.5
  - scvi-tools=0.20.3
  - seaborn-base=0.12.2
  - session-info=1.0.0
  - setuptools=67.6.1
  - simpful=2.11.1
  - sip=6.7.9
  - slepc=3.17.1
  - slepc4py=3.17.1
  - smart_open=7.0.1
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sparsehash=2.0.4
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - stdlib-list=0.8.0
  - suitesparse=5.10.1
  - superlu=5.2.2
  - superlu_dist=7.2.0
  - svt-av1=1.4.1
  - swifter=1.4.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tblib=1.7.0
  - tensorflow-deps=2.9.0
  - texttable=1.6.7
  - threadpoolctl=3.1.0
  - tifffile=2023.8.12
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=2.0.0
  - torchmetrics=0.11.4
  - torchvision=0.15.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing=3.10.0.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - x264=1!164.3095
  - x265=3.5
  - xlrd=1.2.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - adjusttext==0.8
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anndata2ri==1.1
      - appdirs==1.4.4
      - arboreto==0.1.6
      - argcomplete==3.0.5
      - argh==0.28.1
      - asciitree==0.3.3
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.2
      - biofluff==3.0.4
      - biothings-client==0.3.0
      - bokeh==3.1.0
      - boltons==23.0.0
      - bx-python==0.9.0
      - cachetools==5.3.0
      - cell2cell==0.6.8
      - click==8.1.3
      - cmake==3.26.3
      - compress-json==1.0.8
      - configparser==5.3.0
      - cooler==0.9.1
      - ctxcore==0.2.0
      - cython==0.29.34
      - cytoolz==0.12.1
      - dask==2023.4.0
      - dateparser==1.1.8
      - decoupler==1.4.0
      - dill==0.3.6
      - diskcache==5.6.1
      - distributed==2023.4.0
      - dunamai==1.16.0
      - elpigraph-python==0.2.7
      - exceptiongroup==1.1.1
      - face==20.1.1
      - fcsparser==0.2.6
      - feather-format==0.4.1
      - flatbuffers==23.3.3
      - frozendict==2.3.7
      - frozenlist==1.3.3
      - gast==0.4.0
      - genomepy==0.16.1
      - get-version==3.5.4
      - gffutils==0.11.1
      - gimmemotifs==0.18.0
      - glom==23.3.0
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.0
      - gseapy==1.0.3
      - harmonyts==0.1.4
      - hicmatrix==15
      - htseq==2.0.3
      - inflect==6.0.4
      - iniconfig==2.0.0
      - interlap==0.2.7
      - ipy==1.1
      - iteround==1.0.4
      - jaro-winkler==2.0.3
      - keras==2.12.0
      - kneed==0.8.2
      - liana==0.1.8
      - libclang==16.0.0
      - logomaker==0.8
      - loguru==0.7.0
      - loompy==3.0.7
      - lxml==4.9.3
      - markdown==3.4.3
      - matplotlib==3.5.1
      - matplotlib-venn==0.11.10
      - mizani==0.8.1
      - moods-python==1.9.4.1
      - multidict==6.0.4
      - multiprocess==0.70.14
      - multiprocessing-on-dill==3.5.0a4
      - muon==0.1.3
      - mygene==3.2.2
      - mysql-connector-python==8.0.33
      - ndindex==1.7
      - networkx==2.8.8
      - norns==0.1.6
      - nose==1.3.7
      - numpy-groupies==0.9.20
      - oauthlib==3.2.2
      - omnipath==1.0.6
      - palantir==1.2
      - palettable==3.3.1
      - pandas==1.5.3
      - paramiko==3.3.1
      - parse==1.19.0
      - phenograph==1.5.7
      - plotly==5.14.1
      - plotnine==0.10.1
      - plottable==0.1.5
      - pluggy==1.0.0
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybedtools==0.9.0
      - pybigwig==0.3.22
      - pycurl==7.45.2
      - pydantic==1.10.7
      - pyfaidx==0.7.2.1
      - pygam==0.8.0
      - pygenometracks==3.8
      - pynacl==1.5.0
      - pynvml==11.5.0
      - pypath-omnipath==0.15.7
      - pyreadr==0.4.9
      - pysam==0.21.0
      - pyscenic==0.12.1
      - pysftp==0.2.9
      - pytest==7.3.1
      - python-igraph==0.10.4
      - python-utils==3.5.2
      - pytorch-ignite==0.4.11
      - pytz-deprecation-shim==0.1.0.post0
      - qnorm==0.8.1
      - rdata==0.9
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - rpy2==3.5.11
      - rsa==4.9
      - scfates==1.0.2
      - scglue==0.3.2
      - scib-metrics==0.3.3
      - scselpy==1.1.3
      - seaborn==0.11.2
      - shapely==2.0.1
      - simplegeneric==0.8.1
      - simplejson==3.19.1
      - simpleppt==1.1.3
      - six==1.15.0
      - sklearn==0.0.post4
      - soupsieve==2.4.1
      - sparse==0.14.0
      - sqlparse==0.4.4
      - statannotations==0.5.0
      - support-developer==1.0.5
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - tensorflow-estimator==2.12.0
      - tensorly==0.8.1
      - termcolor==2.3.0
      - timeloop==1.0.2
      - tzlocal==4.3
      - ucsc-genomes-downloader==1.1.26
      - userinput==1.0.20
      - validate-email==1.3
      - validate-version-code==1.0.4
      - validators==0.20.0
      - werkzeug==2.2.3
      - wrapt==1.14.1
      - xarray==2023.7.0
      - xdg==6.0.0
      - xxhash==3.2.0
      - xyzservices==2023.2.0
      - yarl==1.9.1
